server:
  port: ${PORT:8080}  

spring:
  application:
    name: auth

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://tortas-mejorado-discovery.onrender.com/eureka/
  instance:
    prefer-ip-address: false
    hostname: ${RENDER_EXTERNAL_HOSTNAME}
    non-secure-port: 80
    secure-port-enabled: true
    secure-port: 443
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# Timeouts por si otros microservicios usan Feign para hablar con usuarios
feign:
  client:
    config:
      default:
        connectTimeout: 5000     # tiempo para establecer conexión (5s)
        readTimeout: 5000        # tiempo para esperar respuesta (5s)
