server:
  port: ${PORT:8080}  

spring:
  application:
    name: auth

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://tortas-mejorado-discovery.onrender.com/eureka/  # Agrega /eureka/
  instance:
    prefer-ip-address: true
    non-secure-port: ${PORT:8080}
    secure-port-enabled: true
    secure-port: 443
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# Configuración adicional si necesitas base de datos
# spring:
#   datasource:
#     url: ${DATABASE_URL}
#     username: ${DB_USERNAME}
#     password: ${DB_PASSWORD}
#   jpa:
#     hibernate:
#       ddl-auto: update

