server:
  port: ${PORT:8761}

spring:
  application:
    name: discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    
  instance:
    hostname: tortas-mejorado-discovery.onrender.com
