server:
  port: ${PORT:8761}  # Usa el puerto asignado por Render o 8761 en local

spring:
  application:
    name: discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    
  instance:
    hostname: ${HOSTNAME:localhost}  # Render asigna automáticamente un hostname
