server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      websocket:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/**
        - id: usuarios
          uri: lb://USUARIOS
          predicates:
            - Path=/api/v1/usuarios/**
        - id: servicio-productos
          uri: lb://SERVICIO-PRODUCTOS
          predicates:
            - Path=/api/v1/productos/**
        - id: servicio-ordenes
          uri: lb://SERVICIO-ORDENES
          predicates:
            - Path=/api/v1/ordenes/**
        - id: servicio-ventas
          uri: lb://SERVICIO-VENTAS
          predicates:
            - Path=/api/v1/ventas/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://tortas-mejorado-discovery.onrender.com/eureka/
  instance:
    prefer-ip-address: true
    non-secure-port: ${PORT:8080}
    secure-port-enabled: true
    secure-port: 443
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler: DEBUG
    org.springframework.web.reactive.DispatcherHandler: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG