server:
  port: 8222

spring:
  application:
    name: gateway

  cloud:
    gateway:
      websocket:
        enabled: true
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/**

        - id: usuarios
          uri: lb://USUARIOS
          predicates:
            - Path=/api/v1/usuarios/**

        - id: servicio-productos
          uri: lb://SERVICIO-PRODUCTOS
          predicates:
            - Path=/api/v1/productos/**

        - id: servicio-ordenes
          uri: lb://SERVICIO-ORDENES
          predicates:
            - Path=/api/v1/ordenes/**
        
        - id: servicio-ventas
          uri: lb://SERVICIO-VENTAS
          predicates:
            - Path=/api/v1/ventas/**



eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler: DEBUG
    org.springframework.web.reactive.DispatcherHandler: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    com.netflix.discovery: INFO
