server:
  port: 8060

spring:
  application:
    name: servicio-ventas
eureka:
  instance:
    hostname: tortas-mejorado-discovery.onrender.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://tortas-mejorado-discovery.onrender.com


external:
  api:
    exchangerate:
      base-url: https://api.frankfurter.app

logging:
  level:
    com.example.servicio_ordenes: DEBUG
    org.springframework.web: INFO

