server:
  port: 8070

spring:
  application:
    name: servicio-productos
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true

external:
  api:
    exchangerate:
      base-url: https://api.frankfurter.app

logging:
  level:
    com.example.servicio_ordenes: DEBUG
    org.springframework.web: INFO

