server:
  port: 8090

spring:
  application:
    name: usuarios

eureka:
  instance:
    hostname: tortas-mejorado-discovery.onrender.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://tortas-mejorado-discovery.onrender.com
