server:
  port: 8090

spring:
  application:
    name: usuarios

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: false 
    service-url:
      defaultZone: http://localhost:8761/eureka/
